# Numpy

In [2]:
import numpy as np 

In [3]:
my_lst =[1,2,3,4,5]
arr = np.array(my_lst)

In [4]:
type(arr)

numpy.ndarray

In [5]:
print(arr)

[1 2 3 4 5]


In [6]:
arr

array([1, 2, 3, 4, 5])

In [7]:
arr.shape

(5,)

In [10]:
#multidimensional array
my_lst1 = [1,2,3,4,5]
my_lst2 = [6,7,8,9,10]
my_lst3 = [11,12,13,14,15]
arr = np.array([my_lst1, my_lst2, my_lst3])

In [11]:
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [12]:
arr.shape

(3, 5)

In [14]:
arr.reshape(5, 3)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15]])

In [15]:
arr.reshape(1, 15)

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15]])

# Indexing

In [16]:
arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15])

In [17]:
arr[5]

np.int64(6)