# Numpy

In [3]:
import numpy as np 

In [4]:
my_lst =[1,2,3,4,5]
arr = np.array(my_lst)

In [5]:
type(arr)

numpy.ndarray

In [6]:
print(arr)

[1 2 3 4 5]


In [7]:
arr

array([1, 2, 3, 4, 5])

In [8]:
arr.shape

(5,)

In [9]:
#multidimensional array
my_lst1 = [1,2,3,4,5]
my_lst2 = [6,7,8,9,10]
my_lst3 = [11,12,13,14,15]
arr = np.array([my_lst1, my_lst2, my_lst3])

In [10]:
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [11]:
arr.shape

(3, 5)

In [12]:
arr.reshape(5, 3)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15]])

In [13]:
arr.reshape(1, 15)

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15]])

# Indexing

In [14]:
arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15])

In [15]:
arr[5]

np.int64(6)

In [16]:
#multidimensional array
my_lst1 = [1,2,3,4,5]
my_lst2 = [6,7,8,9,10]
my_lst3 = [11,12,13,14,15]
arr = np.array([my_lst1, my_lst2, my_lst3])

In [17]:
print(arr)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


In [18]:
arr[0:2,0:2]

array([[1, 2],
       [6, 7]])

In [19]:
arr[1:3,2:4]

array([[ 8,  9],
       [13, 14]])

In [20]:
arr= np.arange(1,11)

In [21]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [22]:
np.linspace(1,10,50)

array([ 1.        ,  1.18367347,  1.36734694,  1.55102041,  1.73469388,
        1.91836735,  2.10204082,  2.28571429,  2.46938776,  2.65306122,
        2.83673469,  3.02040816,  3.20408163,  3.3877551 ,  3.57142857,
        3.75510204,  3.93877551,  4.12244898,  4.30612245,  4.48979592,
        4.67346939,  4.85714286,  5.04081633,  5.2244898 ,  5.40816327,
        5.59183673,  5.7755102 ,  5.95918367,  6.14285714,  6.32653061,
        6.51020408,  6.69387755,  6.87755102,  7.06122449,  7.24489796,
        7.42857143,  7.6122449 ,  7.79591837,  7.97959184,  8.16326531,
        8.34693878,  8.53061224,  8.71428571,  8.89795918,  9.08163265,
        9.26530612,  9.44897959,  9.63265306,  9.81632653, 10.        ])

In [23]:
#copy() function and broadcasting in numpy

In [24]:
arr[3:] = 100

In [25]:
arr

array([  1,   2,   3, 100, 100, 100, 100, 100, 100, 100])

In [26]:
arr1 = arr

In [27]:
arr1 = arr.copy()

In [28]:
#Some conditions very useful in exploratory data analysis

val = 2

In [29]:
arr*2

array([  2,   4,   6, 200, 200, 200, 200, 200, 200, 200])

In [30]:
arr<2

array([ True, False, False, False, False, False, False, False, False,
       False])

In [32]:
arr[arr>10]

array([100, 100, 100, 100, 100, 100, 100])

In [34]:
np.ones(2)

array([1., 1.])

In [35]:
np.random.rand(5,7)

array([[0.25452668, 0.69971083, 0.60833129, 0.31652103, 0.80356872,
        0.56787862, 0.45355337],
       [0.49040132, 0.04425889, 0.27633737, 0.06513592, 0.90034814,
        0.82382421, 0.79909528],
       [0.96534165, 0.48218304, 0.95975264, 0.39646506, 0.64187865,
        0.56532777, 0.31403306],
       [0.26046429, 0.52635158, 0.85709408, 0.56677368, 0.37538363,
        0.44031033, 0.56187861],
       [0.00976889, 0.35921376, 0.03987459, 0.23970643, 0.08629568,
        0.0953804 , 0.81228287]])

In [38]:
arr_ex = np.random.randn(4,4)

In [39]:
arr_ex

array([[ 0.2763743 , -1.47083955, -0.65337289, -0.3520089 ],
       [ 1.98102635, -0.15178475,  0.08297616,  0.49337882],
       [-1.54713812, -1.20890345, -0.20849729, -0.01355522],
       [-0.87781501,  0.05340086, -0.88931143, -0.21943449]])

In [40]:
np.random.randint(1,454,6)

array([181, 427, 136, 282,  98, 112], dtype=int32)