# Numpy

In [2]:
import numpy as np 

In [3]:
my_lst =[1,2,3,4,5]
arr = np.array(my_lst)

In [4]:
type(arr)

numpy.ndarray

In [5]:
print(arr)

[1 2 3 4 5]


In [6]:
arr

array([1, 2, 3, 4, 5])

In [7]:
arr.shape

(5,)

In [10]:
#multidimensional array
my_lst1 = [1,2,3,4,5]
my_lst2 = [6,7,8,9,10]
my_lst3 = [11,12,13,14,15]
arr = np.array([my_lst1, my_lst2, my_lst3])

In [11]:
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [12]:
arr.shape

(3, 5)

In [14]:
arr.reshape(5, 3)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15]])

In [15]:
arr.reshape(1, 15)

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15]])

# Indexing

In [16]:
arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15])

In [17]:
arr[5]

np.int64(6)

In [18]:
#multidimensional array
my_lst1 = [1,2,3,4,5]
my_lst2 = [6,7,8,9,10]
my_lst3 = [11,12,13,14,15]
arr = np.array([my_lst1, my_lst2, my_lst3])

In [19]:
print(arr)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


In [23]:
arr[0:2,0:2]

array([[1, 2],
       [6, 7]])

In [25]:
arr[1:3,2:4]

array([[ 8,  9],
       [13, 14]])

In [28]:
arr= np.arange(1,11)

In [30]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [32]:
np.linspace(1,10,50)

array([ 1.        ,  1.18367347,  1.36734694,  1.55102041,  1.73469388,
        1.91836735,  2.10204082,  2.28571429,  2.46938776,  2.65306122,
        2.83673469,  3.02040816,  3.20408163,  3.3877551 ,  3.57142857,
        3.75510204,  3.93877551,  4.12244898,  4.30612245,  4.48979592,
        4.67346939,  4.85714286,  5.04081633,  5.2244898 ,  5.40816327,
        5.59183673,  5.7755102 ,  5.95918367,  6.14285714,  6.32653061,
        6.51020408,  6.69387755,  6.87755102,  7.06122449,  7.24489796,
        7.42857143,  7.6122449 ,  7.79591837,  7.97959184,  8.16326531,
        8.34693878,  8.53061224,  8.71428571,  8.89795918,  9.08163265,
        9.26530612,  9.44897959,  9.63265306,  9.81632653, 10.        ])

In [33]:
#copy() function and broadcasting in numpy

In [37]:
arr[3:] = 100

In [38]:
arr

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [39]:
arr1 = arr

In [ ]:
arr1 = arr.copy()

In [ ]:
#Some conditions very useful in exploratory data analysis

val = q